tests-always-included/wick

- formulas/wick-base/functions/wick-on-exit
Just finding my way around git hub's workings.
> Corrected spelling

- lib/wick-port-up
This function takes 2 variables, 1st is tcp or udp and 2nd is a port number. It returns either UP, DOWN or an error message.
> Check to confirm whether a port is listening.

- formulas/nodejs/README.md
- formulas/nodejs/run
Now supports adding the version as an option.
> Supports Specification Version

- formulas/README.md
- formulas/python-virtualenv/README.md
- formulas/python-virtualenv/run
Installs the Python virtual environment utility.
> Added a simple python-virtualenv formula

- formulas/redis/README.md
- formulas/redis/functions/redis-set-config-line
- formulas/redis/run
So that they are allowed to cluster if they use AUTH
> Allowing user to pass master-password

- formulas/README.md
- formulas/ntp/README.md
- formulas/ntp/run
Created formula to install the ntp package and ntpdate utility.
> Created NTP formula

- lib/wick-log
As discussed earlier.
Test with results can be found here:
https://gist.github.com/baelish/b638181a69a46690a3ef8a77b2ea49aa
> Adding tag to syslog, separated facility/priority

- formulas/wick-base/explorers/machine-type
- formulas/wick-base/explorers/os-version
aws takes a very long time to fail.
> Machine type order

- formulas/wick-base/README.md
- formulas/wick-base/explorers/init-system
- formulas/wick-base/explorers/os-version
New explorer.  I will need this to switch between `chkconfig` and the like.
> Init system

- tests/lib/wick-array-join.bats
Because I thought it might not be working.  It is, but at least we
got a test out of it
> adding test

- tests/lib/wick-array-join.bats
Not sure how I managed those mistakes
> Wick array join test

- formulas/wick-base/functions/wick-service-add-dependency-sysv
Made a mistake.  Luckily nothing uses this yet
> fixing sed expression

- formulas/wick-base/functions/wick-service-add-dependency-sysv
or there may be multiple spaces
> because there may or may not be a space

- formulas/iptables/functions/iptables-save
I apparently had not tested centos path well enough
> The command "services" does not exist

- formulas/hostname/files/set-hostname
This was accidentally removed in a earlier merge request
> Replacing dots with dashes

- formulas/wick-base/functions/wick-service-is-running
- formulas/wick-base/functions/wick-service-reload
- formulas/wick-base/functions/wick-service-restart
- formulas/wick-base/functions/wick-service-start
- formulas/wick-base/functions/wick-service-stop
I missed these when I did it originally.
> using systemctl for systemd

- formulas/wick-base/functions/wick-service-is-running
- formulas/wick-base/functions/wick-service-reload
- formulas/wick-base/functions/wick-service-restart
- formulas/wick-base/functions/wick-service-start
- formulas/wick-base/functions/wick-service-stop
service may not exist in some rare cases
> running init scripts directly

- doc/argument-processing.md
- formulas/wick-base/functions/wick-service
See https://github.com/fidian/gg-core/pull/7 for a description of the problem and the steps to replicate.
> Fixes array slices so they work in older bash

- doc/argument-processing.md
- doc/bash-strict-mode.md
- formulas/wick-base/functions/wick-service
Found on tests-always-included/wick#113
This was the solution first suggested by fidian/gg-core#7
> Fixing bug with array substrings

- bin/wick-explorer
> Caching explorer output

- formulas/wick-base/functions/wick-package-yum
Without the -y you may get questions like these:
```
Retrieving key from http://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
Importing GPG key 0x8ECCE87C:
Userid: "infrastructure-eng <infrastructure-eng@newrelic.com>"
From  : http://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
Is this ok [y/N]:
```
> We don't want to answer questions.
